name: Build


on:
 push:
  branches:
  - main
 
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with: 
       dotnet-version: 7.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Publish
      run: dotnet publish -c Release

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
       server: ${{ secrets.FTP_SERVER }}
       username: ${{ secrets.FTP_USERNAME }}
       password: ${{ secrets.FTP_PASSWORD }}
     

  


