name: Build


on:
 push:
  branches:
  - main
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with: 
       dotnet-version: 7.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Publish
      run: dotnet publish -c Release -o WebApplication1/bin/Release/net7.0/publish/
    
    - name: List output files
      run: ls -l WebApplication1/bin/Release/net7.0/publish/

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
       server: ftp.asgarbabayev.com
       username: ${{ secrets.FTP_USERNAME }}
       password: ${{ secrets.FTP_PASSWORD }}
       local-dir: WebApplication1/bin/Release/net7.0/publish/
       server-dir: ./httpdocs/
       protocol: ftps
       git-ftp-args: --insecure 
     

  


